nameOverride: "tsn-service"
fullnameOverride: "tsn-service"

replicaCount: 1
annotations: {}

image:
  repository: ghcr.io/jittinabraham/opencnc_tsn-service/tsn-service
  tag: 73a286e9
  pullPolicy: IfNotPresent
  pullSecrets: []

resources:
  requests:
    cpu: 0.5
    memory: 512Mi

service:
  type: ClusterIP

ports:
  grpc:
    main: 5150
    monitor: 5151

nodeSelector: {}

tolerations: []

affinity: {}

etcd:
  username: root
  secretName: etcd
  endpoints:
    - "http://etcd.opencnc.svc.cluster.local:2379"
    
tls:
  enabled: true
  secretName: opencnc-shared-cert
  mountPath: /certs


